version: "3.2"
services:
  api:
    restart: "always"
    ports:
      - 5000:5000
    build: "./server"
    links:
      - db
    environment:
      - DB_HOST=postgres
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - "./server:/go/src/app"
      - "/go/src/app/vendor"
    networks:
      infranet:
        aliases:
          - "postgres"
  db:
    image: postgres:9.3
    restart: "always"
    ports:
      - 5432:5432
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    build: "./db"
    volumes:
      - pg_data:/var/lib/postgresql/data

    networks:
      infranet:
        aliases:
          - "postgres"

networks:
  infranet:

volumes:
  pg_data:
