version: "3.2"
services:
  db:
    restart: "always"
    ports:
      - 5432:5432
    environment:
      - "DB_USER=bperf"
      - "DB_PASSWORD=bperf"
      - "DB_DATABASE=bperf"
      - "POSTGRES_PASSWORD=password"
    build: "./db"
    networks:
      infranet:
        aliases:
          - "postgres"

networks:
  infranet:
