version: 2.1

references:
  server_image: &server_image "circleci/golang:1.11.5"
  client_image: &client_image "circleci/node:9.8.0"
  db_image: &db_image postgres:10.2-alpine
  server_test: &server_test
    run:
      name: Server
      command: |
        go test ./server

  install_node_modules: &install_node_modules
    run:
      name: Install node_modules
      command: |
        npm install --no-save
        npm cache verify

  install_vendor: &install_vendor
    run:
      name: Install vendor
      command: |
        cd server && dep ensure

  client_test: &client_test
    run:
      name: Client
      command: |
        npm run type

jobs:
  server:
    working_directory: /go/src/github.com/kogai/bperf
    docker:
      - image: *server_image
      - image: *db_image
    steps:
      - checkout
      - *install_vendor
      - *server_test
  client:
    working_directory: ~/bperf
    docker:
      - image: *client_image
    steps:
      - checkout
      - *install_node_modules
      - *client_test

workflows:
  version: 2
  myjob:
    jobs:
      - server
      - client
