version: 2.1

references:
  server_image: &server_image "circleci/golang:1.11.5"
  client_image: &client_image "circleci/node:9.8.0"
  db_image: &db_image postgres:9.3
  api_test: &api_test
    run:
      name: API
      command: |
        go test ./api

  install_node_modules: &install_node_modules
    run:
      name: Install node_modules
      command: |
        npm install --no-save
        npm cache verify

  install_vendor: &install_vendor
    run:
      name: Install vendor
      command: |
        cd api && dep ensure

  web_test: &web_test
    run:
      name: Client
      command: |
        npm run type

jobs:
  api:
    working_directory: /go/src/github.com/kogai/bperf
    docker:
      - image: *server_image
      - image: *db_image

    steps:
      - checkout
      - *install_vendor
      - *api_test
  web:
    working_directory: ~/bperf
    docker:
      - image: *client_image
    steps:
      - checkout
      - *install_node_modules
      - *web_test

workflows:
  version: 2
  myjob:
    jobs:
      - api
      - web
